os: linux
dist: trusty
sudo: required

language: cpp
compiler: gcc

install:
    # Upgrade g++ to 4.9 and install R
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq g++-4.9 r-base
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50

    # Allow non-sudo `R CMD INSTALL` during `make test` (necessary because of R version and/or Travis user?)
    - sudo chmod o+w /usr/local/lib/R/site-library

    - $CXX --version
    - R --version

script:
    # Run tests
    - make test

after_success:
    # Publish code coverage
    - bash <(curl -s https://codecov.io/bash) -X coveragepy
